### PR TITLE
Add lights, textures, and some GX functions

### PR DESCRIPTION
**Pull request by 1011X**
Sorry that the PR is so big, didn't know GX was the biggest module in the library... :sweat_smile:

Summary of changes:
+ There's now light objects! You can create, adjust, and load lights into the system. Almost all light methods should be in there now (except for `GX_InitLightDirv()` and `GX_InitLightPosv()`), and you can load them with `Gx::load_light()`. `Gx::load_light_idx()` doesn't currently work since some prerequisite functions haven't been implemented yet.
+ You can create textures! You can create, adjust, inspect, and load textures into the system now. I think adding user data is the only thing that's missing.
+ Fifos (aka queues) can now be created, adjusted, inspected, and loaded. The loading functions `Gx::set_gp_fifo()` and `Gx::set_cpu_fifo()` currently take ownership of the struct due to the pointer to mutable data.
+ Added some much needed safety comments in the construction of the objects above.
+ Textures and fifos take lifetime parameters because they hold pointers to data and I figured adding such annotations would make things safer.
+ `Color` is now a wrapper around `GXColor`.
+ Made various enums for the different options that can be picked in a function, including the ones for measuring performance like `Perf0` and `Perf1`, along with the appropriate functions that use them.
+ Added some simple function calls like `Gx::abort_frame()`, `Gx::clear_bounding_box()`, etc.

### CODE REVIEW

**Comment by ProfElements** [comment]
After looking over it a little. It looks great. One or two things.

PixelFormat is sadly still just a u8 instead of an enum.

The example's assert if not used within Gx::init already might be good to include there

**Comment by 1011X** [comment]
> PixelFormat is sadly still just a u8 instead of an enum.

Gosh, so demanding :stuck_out_tongue: 

Yeah I've considered making an enum for it, but there are so many variants and aliases to values and bitop expressions that I've held back on it until I figure out what a good representation would look like.

> The example's assert if not used within Gx::init already might be good to include there

If you're referring to the asserts in the example's `Display::new()`, they're there because of the safety requirements by the allocation API. `Gx::init()` does not allocate and just uses the given buffer directly, so I don't see a need to include them there.

**Comment by ProfElements** [comment]
> If you're referring to the asserts in the example's `Display::new()`, they're there because of the safety requirements by the allocation API. `Gx::init()` does not allocate and just uses the given buffer directly, so I don't see a need to include them there.

Understandable
 
> Yeah I've considered making an enum for it, but there are so many variants and aliases to values and bitop expressions that I've held back on it until I figure out what a good representation would look like.

This is exactly why I havent touched it either. Its really hard when there are just too many different  things that really shoud be seperate.

Then it LGTM

**Review by FrictionlessPortals — APPROVED** [review]
Great! LGTM, time to merge!

**Pull request merged**
