### PR TITLE
Fix docs.rs and CI builds and convert libogc doxygen comments to rust-style

### PR DESCRIPTION
**Pull request by Setadokalo**
~~This was created on top of #91, so I'm marking it as a draft until that PR is merged.~~

Fixes ogc-rs failing to build documentation on docs.rs by just skipping the dependency logic in `build.rs` when it's building on docs.rs, which is fine since it's not actually trying to link anything. Ogc-sys will most likely not produce correct documentation consistently if it's ever exposed, since it *does* rely on linking to update `ogc.rs`, but that should be fine since it's not on crates.io (and if you're pulling from the git repo, you can and should be using a local `cargo doc` run). This also fixes the `cargo doc` generation by converting the doxygen formatted comments from libogc into rust styled docs using `doxygen-rs`.

### CODE REVIEW

**Comment by Setadokalo** [comment]
side note, should we really be tracking changes to `ogc-sys/ogc.rs`? It's generated as part of the build process, right? Seems like tracking it in git is just extra noise.

**Comment by ProfElements** [comment]
> side note, should we really be tracking changes to `ogc-sys/ogc.rs`? It's generated as part of the build process, right? Seems like tracking it in git is just extra noise.

Originally we didn't always do a `bindgen` build with the ogc.rs just when something major changed. Its hasn't been made optional again yet.

**Comment by Setadokalo** [comment]
That actually can be fixed in the same way as the docs.rs build, I'll add it.

**Comment by ProfElements** [comment]
Anything else needed from this?

**Comment by Setadokalo** [comment]
Not that I'm aware of. This fixes all the problems I've had with the documentaton (other than the stuff that isn't documented yet at all, but that's a topic for another PR :smile:)

**Comment by ProfElements** [comment]
Cool!! Merged.

**Pull request merged**
