### PR TITLE
Added mp3 playing to ogc-rs

### PR DESCRIPTION
**Pull request by ProfElements**
Haven't tested on console but have tested on dolphin and works (linux x86_64)

### CODE REVIEW

**Comment by TheTechRobo** [comment]
I'll test the example on my physical Wii when I get home from school.

**Comment by ProfElements** [comment]
Thank you

**Comment by TheTechRobo** [comment]
Appears my build system is completely broken. :/

```
error: failed to run custom build command for `ogc-sys v0.1.1 (https://github.com/rust-wii/ogc-rs.git?branch=mp3#41cdf731)`

Caused by:
  process didn't exit successfully: `/home/thetechrobo/ogc-rs/examples/template/target/debug/build/ogc-sys-373294b8d436d80c/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-search=native=/opt/devkitpro/devkitPPC/powerpc-eabi/lib
  cargo:rustc-link-search=native=/opt/devkitpro/libogc/lib/wii
  cargo:rustc-link-lib=static=c
  cargo:rustc-link-lib=static=sysbase
  cargo:rustc-link-lib=static=m
  cargo:rustc-link-lib=static=ogc
  cargo:rustc-link-lib=static=asnd
  cargo:rustc-link-lib=static=mad
  cargo:rustc-link-lib=static=aesnd
  cargo:rustc-link-lib=static=bte
  cargo:rustc-link-lib=static=wiiuse
  cargo:rerun-if-changed=wrapper.h

  --- stderr
  /opt/devkitpro/libogc/include/gctypes.h:9:10: fatal error: 'stdbool.h' file not found
  thread 'main' panicked at 'Unable to generate bindings: ClangDiagnostic("/opt/devkitpro/libogc/include/gctypes.h:9:10: fatal error: 'stdbool.h' file not found\n")', /home/thetechrobo/.cargo/git/checkouts/ogc-rs-e9db435a22d7839e/41cdf73/ogc-sys/build.rs:99:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

No idea what's wrong.

**Comment by TheTechRobo** [comment]
Is the MP3 copyrighted?

**Comment by ProfElements** [comment]
The mp3 is just a random one I found on youtube. It should probably changed to something better

**Comment by ProfElements** [comment]
Not that I know of

**Comment by TheTechRobo** [comment]
I tried `sudo dkp-pacman -Syu` and `sudo dkp-pacman -S wii-dev` :/

**Comment by TheTechRobo** [comment]
I think my build system is completely broken. Could you just send an elf?

**Comment by ProfElements** [comment]
https://filetransfer.io/data-package/lJoZOEBA#link

**Review by TheTechRobo — APPROVED** [review]
Can confirm that this works on real hardware.

**Comment by ProfElements** [comment]
Will merge soon! thank you for testing on real hardware!

**Pull request merged**
