### PR TITLE
Fix data-layout error and 'stdbool.h not found' error

### PR DESCRIPTION
**Pull request by antoineok**
This pull request fixes the error explained in #89 
It also update bindgen and fixes the small type problems brought by the recent DevkitPPC updates
Unfortunately, the exemples still don't compile (see #82 )

### CODE REVIEW

**Comment by ProfElements** [comment]
Unless anyone is opposed. I will merge this in.

**Comment by antoineok** [comment]
there was a lot of new updates since, i'll have to do another pr after

**Comment by ProfElements** [comment]
Okay. sorry for jumping the gun.

**Comment by antoineok** [comment]
No problems, oh, and i also found how to repair the templates, i'll try to push that too

**Pull request merged**
