### PR TITLE
 :bug: fix(embedded-graphics-wii): Use the Gx::color_4u8 instead of ff…

### PR DESCRIPTION
**Pull request by ProfElements**
Made embedded-graphics-wii use Gx::color_4u8 instead og GX_Color4u8 from ffi. 
Added a simple wrapper around Gx::set_clip_mode().
Cargo format as always.

### CODE REVIEW

**Comment by 1011X** [comment]
Since `Gx::set_clip_mode()` itself is already a Rust wrapper for `GX_SetClipMode()`, it'd be more straight-forward to change it so it takes a `bool` instead of `u8`, then add `Gx::enable_clip_mode()` and `Gx::disable_clip_mode()` with no parameters which enable or disable the clip mode respectively.

Also, important detail I found while working on my changes: `GX_CLIP_ENABLE` is `0` and `GX_CLIP_DISABLE` is `1` instead of vice-versa, so `set_clip_mode()` will need to invert its argument before calling `GX_SetClipMode()`.

**Comment by ProfElements** [comment]
> 
> 
> Since `Gx::set_clip_mode()` itself is already a Rust wrapper for `GX_SetClipMode()`, it'd be more straight-forward to change it so it takes a `bool` instead of `u8`, then add `Gx::enable_clip_mode()` and `Gx::disable_clip_mode()` with no parameters which enable or disable the clip mode respectively.
> 
> Also, important detail I found while working on my changes: `GX_CLIP_ENABLE` is `0` and `GX_CLIP_DISABLE` is `1` instead of vice-versa, so `set_clip_mode()` will need to invert its argument before calling `GX_SetClipMode()`.

I didnt want to mess with `Gx::set_clip_mode()`  since some people may just want to translate their C/C++ code into rust so having the option of u8 and using GX_CLIP_ENABLE / GX_CLIP_DISABLE be an option would be nice.

**Comment by ProfElements** [comment]
> Also, important detail I found while working on my changes: `GX_CLIP_ENABLE` is `0` and `GX_CLIP_DISABLE` is `1` instead of vice-versa, so `set_clip_mode()` will need to invert its argument before calling `GX_SetClipMode()`.

the bool canonical truth value for true is 0 while false is 1, which matches up with the costants.

**Comment by FrictionlessPortals** [comment]
LGTM! All good to merge?

**Pull request merged**
