### PR TITLE
Fix: recent devkitppc changes and the examples

### PR DESCRIPTION
**Pull request by antoineok**
Due to the recent devkitppc update, the stdbool.h folder changed yet again. So i fixed that.

The examples are now working again. The solution might not be the best, but it works.

### CODE REVIEW

**Comment by antoineok** [comment]
I just noticed that despite the templates compiling, making an external crate that include ogc-rs won't compile (with the same error this PR fixed on the library itself
)

**Comment by ProfElements** [comment]
Is this ready to merge?

**Comment by antoineok** [comment]
It can be merged, trying the exemples works, however, trying to use the library still seems to fail

**Comment by antoineok** [comment]
and the fact that my IP seems to have been banned from Devkitpro's servers isn't helping me with new updates.

**Comment by Daxorinator** [comment]
> It can be merged, trying the exemples works, however, trying to use the library still seems to fail

Can you elaborate on what you mean here? Is there a specific issue being thrown or is this when you just try to use the library in a non-example context?

**Comment by antoineok** [comment]
Compiling the exemple works without any problem. But trying to import the library in another project (using the git path of my fork) results in the stdbool.h not found error while compiling ogc-rs

**Comment by antoineok** [comment]
the exemple problem was just a stupid error from my part on my project. The problem didn't came from ogc-sys. Sorry about that. I added a fix to automatically add the std include path in the build.rs, so the stdbool.h not found shouldn't appear again if devkitppc's gcc were to change version

**Comment by Setadokalo** [comment]
building using this branch I get fewer linker errors than I did with the old example, but I still get a single `undefined reference to `__end__'` that aborts the linking step.

**Comment by antoineok** [comment]
wierd, i  have no error on both my PC and my laptop

**Comment by antoineok** [comment]
can you open an issue on my fork with the complete log?

**Comment by Daxorinator** [comment]
You don't actually have issues enabled on your fork 😅 Let's keep it here - feel free to open an issue on this repo if it helps for triage, might help some other people who could be having similar issues.

**Comment by antoineok** [comment]
Can someone else try to see if they have the error too?

**Comment by Setadokalo** [comment]
Command + output in a pastebin here
https://pastebin.com/mb0UgG5b

**Comment by antoineok** [comment]
> Command + output in a pastebin here https://pastebin.com/mb0UgG5b

error: linker `powerpc-eabi-gcc` not found
  |
  = note: No such file or directory (os error 2)
  
  You forgot to add DEVKITPPC/bin in the path

**Comment by antoineok** [comment]
Small question, but have you made any change to the code?

**Comment by Setadokalo** [comment]
no, but when I try building it after `cargo clean` it does automatically make some changes to `ogc-sys/src/ogc.rs`. Nothing that looks super relevant, just a few api changes it seems and the version constant bumps to `4.4.0`.

**Comment by antoineok** [comment]
That's wierd, what is your OS and are you sure devkitppc/libogc is on the latest version?

**Comment by Setadokalo** [comment]
Looks like even though I ran the command to *install* it the other night when setting everything back up, I didn't run the right command to *update* the installation. It builds successfully now :smile:

**Comment by ProfElements** [comment]
How far along is this?

**Comment by antoineok** [comment]
Well, it's ready to get merged.

**Pull request merged**
